### Config example, see ./configs folder for templates and variables annotations

name: monusac_aug
profile: hv_monusac
id: 1.0

# 1st - extract patches
data_dir: data_hv_monusac
extract_type: mirror
data_modes:
  - train
  - test
  - valid

# 2nd - training
input_augs: p_linear_2
train_dir:
- train/Annotations
valid_dir:
- valid/Annotations

# 3rd - inference
inf_auto_find_chkpt: true
inf_auto_metric: valid_dice
inf_batch_size: 16

remap_labels: false
inf_data_list:
  - data_hv_monusac/test/Images/
